export const labels = {
    "alert.folderNestedContent.title": "Are you sure you want to delete this folder?",
    "alert.folderNestedContent.text": "This folder is not empty. All nested assets and folders will be permanently deleted.",
    "alert.folderNestedContent.cancel": "Cancel",
    "alert.folderNestedContent.commit": "Delete folder and all contents",
    "alert.deliveryUrlChange.title": "Confirm your changes",
    "alert.deliveryUrlChange.text": "Changing the name of your file will result in a new delivery URL. All existing URLs to this file will break.",
    "alert.deliveryUrlChange.cancel": "Cancel",
    "alert.deliveryUrlChange.commit": "Rename file",
    "alert.deliveryUrlRequired.title": "Update URL aswell?",
    "alert.deliveryUrlRequired.text": "You are about to change the display name of this file. The URL of this file will not change. Do you want to update the URL aswell? Warning: All existing URLs to this file will break.",
    "alert.deliveryUrlRequired.cancel": "Change display name only",
    "alert.deliveryUrlRequired.commit": "Change name and URL",
    "hint.clickToRename": "Click to rename",
} as const