name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Semver Version Bump Type'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    main:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "22.x"
                cache: "pnpm"
            
            - name: Install Dependencies
              run: pnpm install
          
            - name: "Build & Publish to npm"
              id: publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  VERSION_BUMP_TYPE: ${{ github.event.inputs.version }}
              run: pnpm handle-with-care-ci

            - name: "Prepare GitHub Release"
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "chore(release): ${{ steps.publish.outputs.version }}"

            - name: Create GitHub Release
              uses: actions/github-script@v7
              with:
                script: |
                    await github.request('POST /repos/${{ github.repository }}/releases', {
                        tag_name: '${{ steps.publish.outputs.version }}',
                        generate_release_notes: true,
                        draft: false,
                    })
