name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    if: github.repository == 'filenest/filenest' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Install Pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install npm v10
        run: npm install -g npm@10

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-release
          commit: 'chore: release new version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}