name: Version

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    name: Version
    if: github.repository == 'filenest/filenest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.x

      - name: Install npm v10
        run: npm install -g npm@10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Version Packages
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}